upstream auth_up {
    server auth-service:3002 max_fails=3 fail_timeout=10s;
    keepalive 16;
}

upstream monolith_up {
    least_conn;
    server monolith:3000 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream comments_up {
    least_conn;
    server comments-service:3001 max_fails=3 fail_timeout=10s;
    keepalive 16;
}

upstream fanout_up {
    least_conn;
    server fan-out-service:3004 max_fails=3 fail_timeout=10s;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name newsfeed.local localhost;

    location = /healthz {
        access_log off;
        return 200 "nginx ok\n";
    }

    location ^~ /api/internal { return 404; }
    location ~* ^/api/metrics$ { return 404; }

    location = /api/.well-known/jwks.json {
        proxy_pass http://auth_up/.well-known/jwks.json;
        include /etc/nginx/snippets/proxy.conf;
    }

    location = /api/auth/login {
        limit_req zone=login burst=5 nodelay;
        proxy_pass http://auth_up/auth/login;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /api/auth/ {
        limit_req zone=api burst=40 nodelay;
        proxy_pass http://auth_up/auth/;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /api/comments {
        limit_req zone=api burst=40 nodelay;
        proxy_pass http://comments_up/comments;
        include /etc/nginx/snippets/proxy.conf;
    }


    location /api/feed {
        limit_req zone=api burst=40 nodelay;
        proxy_pass http://fanout_up/feed;
        include /etc/nginx/snippets/proxy.conf;
    }

    location /api/ {
        limit_req zone=api burst=40 nodelay;
        limit_conn conns 20;
        proxy_pass http://monolith_up/;
        include /etc/nginx/snippets/proxy.conf;
    }

    location / { return 404; }
}