{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DLQ messages redriven",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(dlq_messages_redriven_total[$__range]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "DLQ messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(dlq_messages_total[$__range]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Lag by topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_lag{service=\"kafka\"})",
     "legendFormat": "{{topic}} / p{{partition}}"
    }
   ]
  },
  {
   "title": "Messages in per second (broker throughput)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{service=\"kafka\", topic!=\"__consumer_offsets\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages produced/consumerd per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_messages_produced_total[5m]))",
     "legendFormat": "{{topic}} - produced"
    },
    {
     "expr": "sum by (topic) (rate(kafka_messages_consumed_total[5m]))",
     "legendFormat": "{{topic}} - consumed"
    }
   ]
  }
 ]
}