{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_dataSize{service=\"mongodb\", database=\"node_kafka_mongo_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{service=\"mongodb\", database=\"node_kafka_mongo_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_pool_connections{service=\"comments-svc\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{service=\"mongodb\", conn_type=\"current\"}",
     "legendFormat": "{{conn_type}}"
    },
    {
     "expr": "mongodb_ss_connections{service=\"mongodb\", conn_type=\"available\"}",
     "legendFormat": "{{conn_type}}"
    }
   ]
  },
  {
   "title": "Operation rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{service=\"mongodb\", legacy_op_type=\"insert\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{service=\"mongodb\", legacy_op_type=\"query\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{service=\"mongodb\", legacy_op_type=\"update\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    },
    {
     "expr": "rate(mongodb_ss_opcounters{service=\"mongodb\", legacy_op_type=\"delete\"}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  }
 ]
}