{
 "title": "Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{service=\"postgres\", datname=\"node_kafka_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection utilization %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{service=\"postgres\"})/sum(pg_settings_max_connections{service=\"postgres\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{service=\"postgres\", datname=\"node_kafka_db\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction success rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(pg_stat_database_xact_commit{service=\"postgres\", datname=\"node_kafka_db\"}[5m]) * 100) / (rate(pg_stat_database_xact_commit{service=\"postgres\"}[5m]) + rate(pg_stat_database_xact_rollback{service=\"postgres\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Application pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pg_pool_connections{state=\"active\"}",
     "legendFormat": "{{service}}-{{state}}"
    },
    {
     "expr": "pg_pool_connections{state=\"waiting\"}",
     "legendFormat": "{{service}}-{{state}}"
    },
    {
     "expr": "pg_pool_connections{state=\"idle\"}",
     "legendFormat": "{{service}}-{{state}}"
    }
   ]
  }
 ]
}